name: JobPortal Build Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Build:
    runs-on: windows-2022

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore JobPortal.sln

      - name: Build the solution
        run: dotnet build JobPortal.sln --no-restore --configuration Release

      - name: Run unit tests
        run: dotnet test JobPortal.Api.Tests.Unit/JobPortal.Api.Tests.Unit.csproj --no-build --configuration Release --verbosity normal
